package com.backend.stockAllocation.enums;

public enum RuleType {
    MINIMUM_VOLUME,
    MINIMUM_SUBSCRIBER_COUNT,
    MAXIMUM_CONCENTRATION,
    SECTOR_CAP,
    MINIMUM_LIQUIDITY,
    RISK_PROFILE_COMPATIBILITY,
    BLACKLIST,
    HOLD_FREEZE,
    MINIMUM_INVESTABLE_AMOUNT,
    SUSPENDED_INSTRUMENT,
    MINIMUM_LIQUORABILITY
}
